### ISSUE TITLE
Pre-gate container tracking search and view screens

### ISSUE THREAD

**Issue by MohamedMouhoumed** [dpcs-dj/Issues#12]
Change Request Description:

Search and View screens for the pre-gate online scan records.

**Comment by sivasreenivas** [comment]
Dear **Team**,

Migrated the change request to UAT in v3.7.71. Currently the menu was enabled only for admin to track the pregate container movement. Please review and close the ticket.

**Regards,
Siva D**

![image](https://user-images.githubusercontent.com/53824291/62599400-cc433b80-b8f4-11e9-9d9f-99f042d4fcf0.png)

**Comment by MohamedMouhoumed** [comment]
![image](https://user-images.githubusercontent.com/53810814/62600462-994e7700-b8f7-11e9-8368-8b657c9e3fe5.png)
