### ISSUE TITLE
pre-gate app

### ISSUE THREAD

**Issue by MohamedMouhoumed** [dpcs-dj/Issues#14]
the DPCR office number should show PK51

![image](https://user-images.githubusercontent.com/53810814/62684075-8f487900-b9c8-11e9-852e-3b1ae19c6cb4.png)

**Comment by sivasreenivas** [comment]
This is very minor issue, need to show the description for the code in the UI. Change will be migrated to UAT on 14.08.2019 release.

**Comment by sivasreenivas** [comment]
Fix has been provided in v3.8.73 please test and close the ticket. Thanks.

![image](https://user-images.githubusercontent.com/53824291/63019506-308d6e80-bea4-11e9-9f0f-b3c4a4816964.png)

**Comment by MohamedMouhoumed** [comment]
________________________________

**Comment by MohamedMouhoumed** [comment]
![image](https://user-images.githubusercontent.com/53810814/63021194-ba3f3b00-bea8-11e9-9279-c467dcbad74b.png)
