### ISSUE TITLE
Berth Application Inbound/Outbound Indicator Amendment for the vessel OOCL SINGAPOR. Rotation No.1900001725

### ISSUE THREAD

**Issue by OSMANALI09** [dpcs-dj/Issues#16]
***Description of the changes***

The Berth Application Inbound/Outbound Indicator of the vessel detailed below need to be amended so that the Terminal Operator can proceed with the remaining validation.

The changes should be as follows:

Inbound/Outbound Indicator: **Both** 

Vessel OPR Details:

Berth Application Number : BA2019080400842
Vessel Name: OOCL SINGAPORE
Voyage No: 030W
Rotation No: 1900001725

![OOCL SINGAPORE_030W_Header_13 08 2019](https://user-images.githubusercontent.com/53811457/62922513-386de580-bdb4-11e9-8734-e3345531150f.jpg)

**Comment by sivasreenivas** [comment]
The support ticket has been raised as BUG which is not in below case, please change it to help wanted. Also please mention the support case ticket raised in the mail as well so that team can address the issue quickly.

**Comment by sivasreenivas** [comment]
Its not an enhancement, Its "help wanted". End user has done the mistake and seeking our help to change to correct indicator by updating in the back-end. Team will update you once the ticket has been  closed.
