### ISSUE TITLE
DPCR APP

### ISSUE THREAD

**Issue by MohamedMouhoumed** [dpcs-dj/Issues#17]
the follow destinations are missing from the app for the DPCR:

- Local 
- Djibouti dry port
- Pk23 free-zone
- Free-zone
- UFZ free-zone
- East Africa

**Comment by sivasreenivas** [comment]
Dear Mohamed,

Modified the Label to Help wanted as it was not BUG or enhancement. Team is working on the changes will first do address the issue in UAT and based on core team review will do the same in PROD.

Thanks,

**Regards,
Siva D**

**Comment by sivasreenivas** [comment]
Dear Mohamed,

Done the requested changes to the discharge list and moved to UAT environment. Please test and confirm the changes. Based on the report will move the same changes to PROD environment.

**Regards,
Siva D**

![image](https://user-images.githubusercontent.com/53824291/62998441-38cdb580-be74-11e9-9eb1-9169ac31c3de.png)

**Comment by MohamedMouhoumed** [comment]
Dear siva,

Note that I have tested the changes as you can see on the image below and it is working as expected. Now waiting for the same changes to be moved PROD environment to close this ticket.
![image](https://user-images.githubusercontent.com/53810814/63326061-1a643000-c334-11e9-80f4-aba7ec0daea8.png)

**Comment by sivasreenivas** [comment]
@Abdirahim0 The change has been tested in UAT and confirmed by the core team member. When the same build is moved to PROD this will be fixed in PROD as well. Please help us to close the ticket.
