### ISSUE TITLE
Loading Operations Process Error Display. Rotation No: 1900001725.

### ISSUE THREAD

**Issue by OSMANALI09** [dpcs-dj/Issues#18]
The Terminal Operator is not able to complete the Loading Operations Process for the vessel detailed below. They are getting the error showing in the attached pic.

Vessel OPR Details:

Berth Application Number : BA2019080400842
Vessel Name: OOCL SINGAPORE
Voyage No: 030W
Rotation No: 1900001725

![OOCL SINGAPORE_030W_Loading OPs Error_13 08 2019](https://user-images.githubusercontent.com/53811457/62940681-c1007c00-bddc-11e9-9c57-254176af21da.png)

**Comment by sivasreenivas** [comment]
Team has done the necessary changes, please review and close the ticket.

**Comment by OSMANALI09** [comment]
The Loading Operations process for this vessel detailed above has been completed successfully.
