### ISSUE TITLE
Vessel ASSIGNMENT: MT DISTYA PUSHTI ( 9179127 ) to SABA INTER-SHIPPING

### ISSUE THREAD

**Issue by OSMANALI09** [dpcs-dj/Issues#19]

**Comment by sivasreenivas** [comment]
Please note that to send the same mail information via mail with approval as well. Approval is mandatory to assist the support cases. 

Note: When ticket is raise please assign it rather than raising to yourself.

**Comment by sivasreenivas** [comment]
Assignment has been done. Close the ticket.

**Comment by OSMANALI09** [comment]
The requested assignment has been successful. The Vessel detailed above has now been re-assigned to the requested Agency ( SABA INTER-SHIPPING ).
