### ISSUE TITLE
rr

### ISSUE THREAD

**Issue by MounaHoussein** [dpcs-dj/Issues#23]
e

**Comment by sivasreenivas** [comment]
Changes are done in both UAT and PROD environments. Please review the changes done and close the ticket. @MounaHoussein @Abdirahim0 

![image](https://user-images.githubusercontent.com/53824291/63147972-706d6680-c008-11e9-8a3a-63ea33905928.png)

![image](https://user-images.githubusercontent.com/53824291/63148089-c04c2d80-c008-11e9-8790-e4999c99edf2.png)
