### ISSUE TITLE
u

### ISSUE THREAD

**Issue by MounaHoussein** [dpcs-dj/Issues#9]
"D

**Comment by MounaHoussein** [comment]
[Siva->] In the new UI upgrade X symbol is not part of the framework. So team will include the RESET button where all the fields will be loaded with default values.
--

**Comment by sivasreenivas** [comment]
Dear Team,
Introduced RESET button for the DPCR report generation page and migrated the same in v3.7.71 to UAT environment. 

Help us to close the ticket. Thanks.

**Regards,
Siva D**

![issue9_resetbutton](https://user-images.githubusercontent.com/53824291/62598646-bf254d00-b8f2-11e9-8014-5013726ae1cc.JPG)

**Comment by MounaHoussein** [comment]
q
